// Shared mall resolution for the browser tools (panel_editor.html, index.html).
//
// Both pages pick their centre from the ?mall= query parameter and resolve its
// files against malls.json -- generated by `python3 malls.py` from the same
// registry the Python pipeline reads, so a page and the simulation can never
// disagree about a mall's inputs. Regenerate malls.json after editing malls.py.
//
// Loaded as a plain script before the page's own script; everything hangs off
// the global MallKit.

const MallKit = (function () {

    // ---- Registry ----------------------------------------------------------

    // Resolve ?mall= against malls.json. Also sets the document title and,
    // when the page provides the hooks, the subtitle and CSV filename hint.
    function load(options) {
        const opts = options || {};
        const requested = new URLSearchParams(window.location.search).get("mall");
        return fetch('malls.json')
            .then(response => {
                if (!response.ok) {
                    throw new Error(`Failed to load malls.json: HTTP ${response.status}. `
                        + `Generate it with: python3 malls.py`);
                }
                return response.json();
            })
            .then(registry => {
                const key = requested || registry.default;
                const config = registry.malls[key];
                if (!config) {
                    const known = Object.keys(registry.malls).join(", ");
                    throw new Error(`Unknown mall '${key}'. Available: ${known}`);
                }
                config.allKeys = Object.keys(registry.malls);
                if (opts.titleSuffix) {
                    document.title = `${config.name} ${opts.titleSuffix}`;
                }
                return config;
            });
    }

    // Offer the other malls as links, so switching does not mean editing the URL.
    function initSwitcher(config, containerId) {
        const container = document.getElementById(containerId || "mall-switcher");
        if (!container || !config.allKeys) return;
        container.innerHTML = "";
        config.allKeys.forEach(key => {
            const link = document.createElement("a");
            link.href = `?mall=${encodeURIComponent(key)}`;
            link.textContent = key;
            link.className = "mall-link" + (key === config.key ? " active" : "");
            container.appendChild(link);
        });
    }

    // ---- Floors ------------------------------------------------------------

    // Floors are discovered from the data a page loads, never declared, so a
    // mall with two levels and one with three both work unconfigured.
    function floorLayer(layers, level) {
        const key = String(level);
        if (!layers[key]) {
            layers[key] = L.featureGroup();
        }
        return layers[key];
    }

    function sortedFloors(layers) {
        return Object.keys(layers).sort((a, b) => {
            const na = parseFloat(a), nb = parseFloat(b);
            if (isNaN(na) || isNaN(nb)) return String(a).localeCompare(String(b));
            return na - nb;
        });
    }

    // Rebuild a .floor-selector button row and any <select> of floors.
    function buildFloorControls(floors, onSelect, selectId) {
        const container = document.querySelector(".floor-selector");
        if (container) {
            container.innerHTML = "";
            floors.forEach(level => {
                const btn = document.createElement("button");
                btn.className = "floor-btn";
                btn.setAttribute("data-floor", level);
                btn.textContent = `Level ${level}`;
                btn.addEventListener("click", () => onSelect(level));
                container.appendChild(btn);
            });
        }
        const select = selectId ? document.getElementById(selectId) : null;
        if (select) {
            select.innerHTML = "";
            floors.forEach(level => {
                const option = document.createElement("option");
                option.value = level;
                option.textContent = `Level ${level}`;
                select.appendChild(option);
            });
        }
    }

    function markActiveFloorButton(level) {
        document.querySelectorAll(".floor-btn").forEach(btn => {
            btn.classList.toggle("active", btn.getAttribute("data-floor") === String(level));
        });
    }

    // ---- Map ---------------------------------------------------------------

    function combinedBounds(layers, floors) {
        let bounds = null;
        floors.forEach(level => {
            const b = floorLayer(layers, level).getBounds();
            if (!b || !b.isValid()) return;
            bounds = bounds
                ? bounds.extend(b)
                : L.latLngBounds(b.getSouthWest(), b.getNorthEast());
        });
        return bounds;
    }

    // Fit once the map container has a real size.
    //
    // A page can reach this before the stylesheet has sized the container, and
    // while Leaflet measures it as 0x0 it resolves ANY bounds to maxZoom --
    // which opens the map blank, zoomed into a few square metres. Waiting for a
    // non-zero size costs a frame or two and is the difference between a usable
    // first view and an apparently broken one.
    function fitWhenSized(map, bounds, attemptsLeft) {
        const remaining = attemptsLeft === undefined ? 60 : attemptsLeft;
        map.invalidateSize();
        const size = map.getSize();
        if (size.x > 0 && size.y > 0) {
            map.fitBounds(bounds, { padding: [10, 10] });
            return;
        }
        if (remaining > 0) {
            requestAnimationFrame(() => fitWhenSized(map, bounds, remaining - 1));
        }
    }

    // Metres per degree of longitude at this latitude, so on-screen view cones
    // are drawn to the same scale the simulation measures with.
    function lonDegToM(latitude) {
        return 111320.0 * Math.cos(latitude * Math.PI / 180);
    }

    // ---- Backdrops ---------------------------------------------------------

    // A mall with no polygon floorplan is drawn as its corridor mesh instead:
    // walkable edges as lines, plus the named entrances, destinations and
    // vertical connectors that make the layout readable enough to place
    // panels against.
    const GRAPH_NODE_STYLES = {
        mall_entrance: { color: '#10b981', radius: 7, label: 'Entrance' },
        shop_entry:    { color: '#f59e0b', radius: 7, label: 'Destination' },
        escalator:     { color: '#d97706', radius: 6, label: 'Escalator' },
        elevator:      { color: '#06b6d4', radius: 6, label: 'Elevator' }
    };

    function renderGraphBackdrop(graph, layers) {
        const nodeById = {};
        (graph.nodes || []).forEach(n => { nodeById[n.id] = n; });

        (graph.edges || []).forEach(edge => {
            const a = nodeById[edge.source], b = nodeById[edge.target];
            if (!a || !b) return;
            // Vertical links join two floors; drawing them on either one is
            // misleading, so they stay out of the floor layers.
            if (String(a.level) !== String(b.level)) return;
            L.polyline([[a.y, a.x], [b.y, b.x]], {
                color: 'rgba(148, 163, 184, 0.35)',
                weight: 2
            }).addTo(floorLayer(layers, a.level));
        });

        (graph.nodes || []).forEach(node => {
            const style = GRAPH_NODE_STYLES[node.type];
            if (!style) return; // plain corridor mesh nodes stay implicit
            const marker = L.circleMarker([node.y, node.x], {
                radius: style.radius,
                fillColor: style.color,
                color: style.color,
                weight: 1.5,
                opacity: 0.9,
                fillOpacity: 0.65
            });
            marker.bindTooltip(node.name || style.label, {
                permanent: false,
                direction: 'top',
                className: 'shop-label-tooltip'
            });
            marker.addTo(floorLayer(layers, node.level));
        });
    }

    // ---- CSV ---------------------------------------------------------------

    function parseCSV(text) {
        const lines = text.split("\n");
        if (lines.length === 0) return [];
        const headers = lines[0].split(",").map(h => h.trim().replace(/^"|"$/g, ''));
        const result = [];
        for (let i = 1; i < lines.length; i++) {
            const line = lines[i].trim();
            if (!line) continue;
            const cols = line.split(",").map(c => c.trim().replace(/^"|"$/g, ''));
            const obj = {};
            for (let j = 0; j < headers.length; j++) {
                obj[headers[j]] = cols[j] || "";
            }
            result.push(obj);
        }
        return result;
    }

    return {
        load, initSwitcher,
        floorLayer, sortedFloors, buildFloorControls, markActiveFloorButton,
        combinedBounds, fitWhenSized, lonDegToM,
        renderGraphBackdrop, parseCSV
    };
})();
